name: Daily Commit for Streak

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight UTC
  workflow_dispatch:

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Git config
        run: |
          git config --local user.email "shaswatp19@gmail.com"
          git config --local user.name "Shaswat19"

      - name: Make random number of commits
        run: |
          RANDOM_COMMITS=$(( (RANDOM % 5) + 1 ))  # Random number between 1 and 5
          echo "Generating $RANDOM_COMMITS commits..."

          for i in $(seq 1 $RANDOM_COMMITS); do
            echo "Commit #$i - $(date)" >> streak.txt
            git add streak.txt
            git commit -m "Streak commit #$i on $(date)"
            sleep 1  # Prevent same timestamp (optional)
          done

          git push
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
