name: Generate Snake Animation
on:
  schedule:
    - cron: "0 */6 * * *" # Runs every 6 hours
  workflow_dispatch: # Allows manual triggering
jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v3
      # Generate the snake SVG
      - uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/snake.svg?color_snake=purple # Purple snake for light mode
            dist/snake-dark.svg?color_snake=purple&palette=github-dark # Purple snake for dark mode
      # Push the generated files to the output branch
      - uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
